biomes:
  - type: Water
    elevation: '<0.12'
    color: 0b4f9c
    walkCost: -1
    terrains:
      # Cold water
      - name: hexOceanIceBergs00
        elevation: '<0.04'
        temperature: '<0.05'
      - name: hexOceanIceBergs01
        elevation: '<0.07'
        temperature: '<0.06'
      - name: hexOceanIceBergs02
        elevation: '<0.1'
        temperature: '<0.07'
      - name: hexOceanIceBergs03
        temperature: '<0.08'
      # Regular water
      - name: hexOcean00
        elevation: '<0.04'
      - name: hexOcean01
        elevation: '<0.07'
      - name: hexOcean02
        elevation: '<0.1'
      - name: hexOcean03
  - type: ExtremeCold
    temperature: '<0.15'
    moisture: '<0.5'
    walkCost: 0.25
    color: 3dc5c5
    mountains:
      - name: hexMountainSnow00
        elevation: '>0.90'
      - name: hexMountainSnow01
        elevation: '>0.87'
      - name: hexMountainSnow02
        elevation: '>0.84'
      - name: hexMountainSnow03
        elevation: '>0.80'
    terrains:
      - name: hexSnowField00
        temperature: '<0.04'
      - name: hexSnowField01
        temperature: '<0.09'
      - name: hexSnowField02
        temperature: '<0.12'
      - name: hexSnowField03
  - type: Cold
    temperature: '<0.3'
    moisture: '<0.8'
    walkCost: 0.5
    color: a9c5c5
    mountains:
      - name: hexHillsColdSnowCovered00
        elevation: '>0.95'
      - name: hexHillsColdSnowCovered01
        elevation: '>0.92'
      - name: hexHillsColdSnowCovered02
        elevation: '>0.89'
      - name: hexHillsColdSnowCovered03
        elevation: '>0.87'
      - name: hexHillsCold00
        elevation: '>0.85'
      - name: hexHillsCold01
        elevation: '>0.83'
      - name: hexHillsCold02
        elevation: '>0.81'
      - name: hexHillsCold03
        elevation: '>0.78'
    terrains:
      # Snow-covered plains (very cold + dry)
      - name: hexPlainsColdSnowCovered00
        temperature: '<0.18'
        moisture: '<0.3'
      - name: hexPlainsColdSnowCovered01
        temperature: '<0.20'
        moisture: '<0.4'
      - name: hexPlainsColdSnowCovered02
        temperature: '<0.22'
        moisture: '<0.45'
      - name: hexPlainsColdSnowCovered03
        temperature: '<0.25'
        moisture: '<0.5'
      # Regular cold plains (cold + wetter) - FIXED: relaxed moisture requirements
      - name: hexPlainsCold00
        temperature: '<0.15'    # Changed from <0.12
        moisture: '>0.55'       # Changed from <0.5 to >0.35 (wetter cold areas)
      - name: hexPlainsCold01
        temperature: '<0.20'    # Changed from <0.18
        moisture: '>0.6'       # Changed from <0.55
      - name: hexPlainsCold02
        temperature: '<0.25'    # Same
        moisture: '>0.65'       # Changed from <0.60
      - name: hexPlainsCold03
        temperature: '<0.30'    # Changed to match parent max
  - type: Jungle
    color: 197a33
    walkCost: 0.9
    temperature: '>0.65'
    moisture: '>0.55'        # Parent requires >0.55
    elevation: '<0.7'
    terrains:
      # Tropical plains (jungle edges - lower moisture) - FIXED
      - name: hexTropicalPlains00
        moisture: '<0.65'      # Changed from <0.5 (was IMPOSSIBLE!)
        temperature: '<0.7'
      - name: hexTropicalPlains01
        moisture: '<0.70'      # Changed from <0.6
        temperature: '<0.75'
      - name: hexTropicalPlains02
        moisture: '<0.75'      # Changed from <0.7
        temperature: '<0.8'
      - name: hexTropicalPlains03
        moisture: '<0.80'      # Same
        temperature: '<0.85'
      # Dense jungle (high moisture)
      - name: hexJungle00
        moisture: '<0.6'
      - name: hexJungle01
        moisture: '<0.7'
      - name: hexJungle02
        moisture: '<0.8'
      - name: hexJungle03               # Fallback - densest jungle
  - type: DeepDesert
    walkCost: 0.35
    moisture: '<0.4'
    temperature: '>0.80'
    elevation: '<0.5'
    color: ed9a21
    mountains:
      - name: hexDesertYellowMesaLarge00
        elevation: '>0.90'
      - name: hexDesertYellowMesaLarge01
        elevation: '>0.87'
      - name: hexDesertYellowMesas00
        elevation: '>0.84'
      - name: hexDesertYellowMesas01
        elevation: '>0.81'
      - name: hexDesertYellowMesas02
        elevation: '>0.78'
      - name: hexDesertYellowMesas03
        elevation: '>0.75'
    terrains:
      - name: hexDesertYellowDirtDunes00
        moisture: '<0.15'
      - name: hexDesertYellowDirtDunes01
        moisture: '<0.18'
      - name: hexDesertYellowDirtDunes02
        moisture: '<0.21'
      - name: hexDesertYellowDirtDunes03
        moisture: '<0.25'
      - name: hexDesertDunes00
        temperature: '<0.85'
      - name: hexDesertDunes01
        temperature: '<0.9'
      - name: hexDesertDunes02
        temperature: '<0.95'
      - name: hexDesertDunes03
  - type: Volcanic
    walkCost: 0.68
    elevation: '>0.3'
    moisture: '<0.5'
    temperature: '>0.7'
    color: ed2e1d
    mountains:
      # Active volcanoes spawn at lava fields
      - name: hexVolcanoActive00
        spawnAtGroup: lava
        minRadius: 5
        spawnChance: 0.05
      - name: hexVolcanoActive01
        spawnAtGroup: lava
        minRadius: 4
        spawnChance: 0.05
      # Dormant volcanoes - FIXED: relaxed temperature
      - name: hexVolcanoDormant00
        temperature: '<0.80'   # Changed from <0.74
        elevation: '>0.9'
        spawnChance: 0.3
      - name: hexVolcanoDormant01
        temperature: '<0.80'   # Changed from <0.74
        elevation: '>0.8'
        spawnChance: 0.2
      - name: hexVolcanoDormant02
        temperature: '<0.80'   # Changed from <0.74
        elevation: '>0.7'
        spawnChance: 0.6
      - name: hexVolcanoDormant03
        temperature: '<0.80'   # Changed from <0.74
        elevation: '>0.6'
        spawnChance: 0.45
    terrains:
      # Lava lakes - FIXED: relaxed conditions
      - name: hexLavaSea00
        key: lava1
        groupKey: lava
        walkCost: -1
        elevation: '<0.85'
        temperature: '>0.8'   # Lowered from >0.90
        moisture: '>0.3'      # Increased from <0.15
      - name: hexLavaSea01
        key: lava2
        groupKey: lava
        walkCost: -1
        elevation: '<0.87'
        temperature: '>0.80'   # Lowered from >0.85
        moisture: '>0.3'      # Increased from <0.20
      - name: hexLavaSea02
        key: lava2
        groupKey: lava
        walkCost: -1
        elevation: '<0.90'
        temperature: '>0.75'   # Lowered from >0.80
        moisture: '>0.3'      # Increased from <0.25
      - name: hexLavaSea03
        key: lava3
        groupKey: lava
        walkCost: -1
        elevation: '<0.95'
        temperature: '>0.70'   # Lowered from >0.75
        moisture: '>0.3'      # Increased from <0.30
      # Hardened lava fields - FIXED: relaxed conditions
      - name: hexLavaField00
        temperature: '>0.80'   # Lowered from >0.90
        moisture: '<0.45'      # Increased from <0.15
        elevation: '>0.8'
      - name: hexLavaField01
        temperature: '>0.77'   # Lowered from >0.85
        moisture: '<0.40'      # Increased from <0.20
        elevation: '>0.75'
      - name: hexLavaField02
        temperature: '>0.74'   # Lowered from >0.80
        moisture: '<0.30'      # Increased from <0.25
        elevation: '>0.70'
      - name: hexLavaField03
        temperature: '>0.70'   # Lowered from >0.75
        moisture: '<0.35'      # Increased from <0.30
        elevation: '>0.66'
      # Ash plains
      - name: hexAshPlains00
        temperature: '>0.85'
        moisture: '<0.35'
      - name: hexAshPlains01
        temperature: '>0.78'
        moisture: '<0.38'
      - name: hexAshPlains02
        temperature: '>0.72'
        moisture: '<0.42'
      - name: hexAshPlains03
        temperature: '>0.65'
        moisture: '<0.45'
  - type: Desert
    walkCost: 0.5
    moisture: '<0.4'
    temperature: '>0.55'
    elevation: '<0.7'
    color: ebdb2b
    mountains:
      - name: hexDesertYellowMesaLarge00
        elevation: '>0.90'
      - name: hexDesertYellowMesaLarge01
        elevation: '>0.87'
      - name: hexDesertYellowMesaLargeOasis00
        elevation: '>0.84'
        spawnChance: 0.8
        minRadius: 10
      - name: hexDesertYellowMesaLargeOasis01
        elevation: '>0.80'
        spawnChance: 0.8
        minRadius: 10
    terrains:
      - name: hexDesertYellowBase00
        moisture: '<0.1'
        temperature: '<0.6'
      - name: hexDesertYellowBase01
        moisture: '<0.2'
        temperature: '<0.65'
      - name: hexDesertYellowBase02
        moisture: '<0.3'
        temperature: '<0.70'
      - name: hexDesertYellowBase03
        moisture: '<0.35'
        temperature: '<0.75'
      # Very dry dirt - FIXED: relaxed moisture requirements
      - name: hexDesertYellowDirt00
        moisture: '<0.1'      # Changed from <0.01 (too restrictive!)
      - name: hexDesertYellowDirt01
        moisture: '<0.2'      # Changed from <0.05
      - name: hexDesertYellowDirt02
        moisture: '<0.3'      # Changed from <0.1
      - name: hexDesertYellowDirt03
  - type: Savanna
    walkCost: 0.9
    moisture: '>0.2'
    temperature: '>0.6'
    elevation: '<0.6'
    color: 8a4807
    mountains:
      - name: hexDesertRedMesaLarge00
        elevation: '>0.90'
        spawnChance: 0.4
      - name: hexDesertRedMountains00
        elevation: '>0.87'
        spawnChance: 0.55
      - name: hexDesertRedMountains01
        elevation: '>0.84'
        spawnChance: 0.6
      - name: hexDesertRedMountains02
        elevation: '>0.81'
        spawnChance: 0.35
      - name: hexDesertRedMountains03
        elevation: '>0.78'
        spawnChance: 0.45
    terrains:
      # Dirt (drier savanna)
      - name: hexDesertRedDirt00
        moisture: '<0.5'
        temperature: '<0.65'
      - name: hexDesertRedDirt01
        moisture: '<0.55'
        temperature: '<0.68'
      - name: hexDesertRedDirt02
        moisture: '<0.60'
        temperature: '<0.74'
      - name: hexDesertRedDirt03
        moisture: '<0.65'
        temperature: '<0.80'
      # Base (mid moisture)
      - name: hexDesertRedBase00
        moisture: '>0.7'
        elevation: '>0.55'
      - name: hexDesertRedBase01
        moisture: '>0.6'
        elevation: '>0.5'
      - name: hexDesertRedBase02
        moisture: '>0.5'
        elevation: '>0.45'
      - name: hexDesertRedBase03
        moisture: '>0.4'
        elevation: '>0.4'
      # Grass (wetter savanna) - FIXED: adjusted ranges
      - name: hexDesertRedGrass00
        moisture: '<0.6'
      - name: hexDesertRedGrass01
        moisture: '<0.7'
      - name: hexDesertRedGrass02
        moisture: '<0.8'
      - name: hexDesertRedGrass03
  - type: Swamp
    walkCost: 0.7
    temperature: '<0.9'
    elevation: '<0.3'
    color: 4dcc8b
    terrains:
      # Bogs (warmer swamps)
      - name: hexBog00
        moisture: '<0.81'
      - name: hexBog01
        moisture: '<0.83'
      - name: hexBog02
        moisture: '<0.85'
      - name: hexBog03
        moisture: '<0.87'
      # Wetlands (colder swamps) - FIXED: relaxed temperature
      - name: hexWetlands00
        temperature: '<0.45'   # Changed from <0.3
        moisture: '>0.87'      # Added to require high moisture
      - name: hexWetlands01
        temperature: '<0.55'   # Changed from <0.4
        moisture: '>0.9'
      - name: hexWetlands02
        temperature: '<0.60'   # Changed from <0.5
        moisture: '>0.93'
      - name: hexWetlands03
        moisture: '>0.8'      # Fallback wetland
  - type: Forest
    walkCost: 1
    color: 2de442
    terrains:
      - name: hexScrublands00
        moisture: '<0.4'
      - name: hexScrublands01
        moisture: '<0.45'
      - name: hexScrublands02
        moisture: '<0.5'
      - name: hexScrublands03
        moisture: '<0.55'
      - name: hexPlains00
        temperature: '<0.5'
      - name: hexPlains01
        temperature: '<0.6'
      - name: hexPlains02
        temperature: '<0.65'
      - name: hexPlains03