biomes:
  - type: Water # Atlas name
    elevation: '<0'
    color: 0b4f9c
    walkCost: -1
    terrains:
      # Warm water
      - name: hexOceanIceBergs00
        elevation: '<-0.25'
        temperature: '<0.05'
      - name: hexOceanIceBergs01
        elevation: '<-0.2'
        temperature: '<0.06'
      - name: hexOceanIceBergs02
        elevation: '<-0.17'
        temperature: '<0.07'
      - name: hexOceanIceBergs03
        temperature: '<0.08'
      - name: hexOcean00
        elevation: '<-0.25'
      - name: hexOcean01
        elevation: '<-0.2'
      - name: hexOcean02
        elevation: '<-0.17'
      - name: hexOcean03
  - type: ExtremeCold
    temperature: '<0.15'
    moisture: '<0.5'
    walkCost: 0.25
    color: 3dc5c5
    mountains:
      - name: hexMountainSnow00
        elevation: '>0.90'
      - name: hexMountainSnow01
        elevation: '>0.87'
      - name: hexMountainSnow02
        elevation: '>0.84'
      - name: hexMountainSnow03
        elevation: '>0.80'
    terrains:
      - name: hexSnowField00
        temperature: '<0.04'
      - name: hexSnowField01
        temperature: '<0.09'
      - name: hexSnowField02
        temperature: '<0.12'
      - name: hexSnowField03
  - type: Cold
    temperature: '<0.3'
    moisture: '<0.8'
    walkCost: 0.5
    color: a9c5c5
    mountains:
      - name: hexHillsColdSnowCovered00
        elevation: '>0.95'
      - name: hexHillsColdSnowCovered01
        elevation: '>0.92'
      - name: hexHillsColdSnowCovered02
        elevation: '>0.89'
      - name: hexHillsColdSnowCovered03
        elevation: '>0.87'
      - name: hexHillsCold00
        elevation: '>0.85'
      - name: hexHillsCold01
        elevation: '>0.83'
      - name: hexHillsCold02
        elevation: '>0.81'
      - name: hexHillsCold03
        elevation: '>0.78'
    terrains:
      - name: hexPlainsColdSnowCovered00
        temperature: '<0.12'
        moisture: '<0.2'
      - name: hexPlainsColdSnowCovered01
        temperature: '<0.18'
        moisture: '<0.25'
      - name: hexPlainsColdSnowCovered02
        temperature: '<0.22'
        moisture: '<0.3'
      - name: hexPlainsColdSnowCovered03
        temperature: '<0.25'
        moisture: '<0.35'
      - name: hexPlainsCold00
        temperature: '<0.12'
        moisture: '<0.5'
      - name: hexPlainsCold01
        temperature: '<0.18'
        moisture: '<0.55'
      - name: hexPlainsCold02
        temperature: '<0.25'
        moisture: '<0.60'
      - name: hexPlainsCold03
  - type: Volcanic
    walkCost: 0.68
    moisture: '<0.4'      # Changed from 0.3 to 0.4 - allows slightly wetter volcanic areas
    temperature: '>0.78'  # Changed from 0.85 to 0.78 - allows slightly cooler volcanic areas
    elevation: '>0.4'
    color: ed2e1d
    mountains:
      - name: hexVolcanoActive00
        elevation: '>0.98'
      - name: hexVolcanoActive01
        elevation: '>0.97'
      - name: hexVolcanoDormant00
        elevation: '>0.84'
      - name: hexVolcanoDormant01
        elevation: '>0.81'
      - name: hexVolcanoDormant02
        elevation: '>0.78'
      - name: hexVolcanoDormant03
        elevation: '>0.75'
    terrains:
      # Lava melt
      - name: hexLavaSea00
        walkCost: -1
        elevation: '>0.8'
      - name: hexLavaSea01
        walkCost: -1
        elevation: '>0.76'
      - name: hexLavaSea02
        walkCost: -1
        elevation: '>0.72'
      - name: hexLavaSea03
        walkCost: -1
        elevation: '>0.78'
      # Lava hard
      - name: hexLavaField00
        temperature: '>0.95'
        moisture: '<0.1'
      - name: hexLavaField01
        temperature: '>0.92'
        moisture: '<0.15'   # Relaxed from 0.1 to 0.15
      - name: hexLavaField02
        temperature: '>0.87'
        moisture: '<0.2'    # Relaxed from 0.1 to 0.2
      - name: hexLavaField03
        temperature: '>0.82'  # Relaxed from implicit to 0.82
        moisture: '<0.25'   # Relaxed from 0.1 to 0.25
      # Ash
      - name: hexAshPlains00
        temperature: '>0.95'
        moisture: '<0.3'    # Added moisture constraint
      - name: hexAshPlains01
        temperature: '>0.90'  # Relaxed from 0.92
        moisture: '<0.35'   # Added moisture constraint
      - name: hexAshPlains02
        temperature: '>0.85'  # Relaxed from 0.87
        moisture: '<0.4'    # Added moisture constraint
      - name: hexAshPlains03
        temperature: '>0.78'  # Relaxed from implicit
  - type: Jungle
    color: 197a33
    walkCost: 0.9
    temperature: '>0.65'
    moisture: '>0.65'
    terrains:
      - name: hexTropicalPlains00
        moisture: '<0.7'
        temperature: '<0.7'
      - name: hexTropicalPlains01
        moisture: '<0.75'
        temperature: '<0.75'
      - name: hexTropicalPlains02
        moisture: '<0.8'
        temperature: '<0.8'
      - name: hexTropicalPlains03
        moisture: '<0.85'
        temperature: '<0.85'
      - name: hexJungle00
        moisture: '<0.9'
      - name: hexJungle01
        moisture: '<0.93'
      - name: hexJungle02
        moisture: '<0.96'
      - name: hexJungle03
  - type: DeepDesert
    walkCost: 0.35
    moisture: '<0.4'
    temperature: '>0.75'
    color: ed9a21
    mountains:
      - name: hexDesertYellowMesaLarge00
        elevation: '>0.90'
      - name: hexDesertYellowMesaLarge01
        elevation: '>0.87'
      - name: hexDesertYellowMesas00
        elevation: '>0.84'
      - name: hexDesertYellowMesas01
        elevation: '>0.81'
      - name: hexDesertYellowMesas02
        elevation: '>0.78'
      - name: hexDesertYellowMesas03
        elevation: '>0.75'
    # Dunes
    terrains:
      - name: hexDesertYellowDirtDunes00
        moisture: '<0.15'
      - name: hexDesertYellowDirtDunes01
        moisture: '<0.18'
      - name: hexDesertYellowDirtDunes02
        moisture: '<0.21'
      - name: hexDesertYellowDirtDunes03
        moisture: '<0.25'
      - name: hexDesertDunes00
        temperature: '<0.8'
      - name: hexDesertDunes01
        temperature: '<0.9'
      - name: hexDesertDunes02
        temperature: '<0.95'
      - name: hexDesertDunes03
  - type: Desert
    walkCost: 0.5
    moisture: '<0.4'
    temperature: '>0.55'
    color: ebdb2b
    mountains:
      - name: hexDesertYellowMesaLarge00
        elevation: '>0.90'
      - name: hexDesertYellowMesaLarge01
        elevation: '>0.87'
      - name: hexDesertYellowMesaLargeOasis00
        elevation: '>0.84'
      - name: hexDesertYellowMesaLargeOasis00
        elevation: '>0.80'
    terrains:
      - name: hexDesertYellowBase00
        moisture: '<0.11'
        temperature: '<0.59'
      - name: hexDesertYellowBase01
        moisture: '<0.14'
        temperature: '<0.63'
      - name: hexDesertYellowBase02
        moisture: '<0.17'
        temperature: '<0.67'
      - name: hexDesertYellowBase03
        moisture: '<0.2'
        temperature: '<0.81'
      - name: hexDesertYellowDirt00
        moisture: '<0.01'
      - name: hexDesertYellowDirt01
        moisture: '<0.05'
      - name: hexDesertYellowDirt02
        moisture: '<0.1'
      - name: hexDesertYellowDirt03
  - type: Savanna
    walkCost: 0.9
    moisture: '>0.2'
    temperature: '>0.6'
    color: 8a4807
    mountains:
      - name: hexDesertRedMesaLarge00
        elevation: '>0.90'
      - name: hexDesertRedMountains00
        elevation: '>0.87'
      - name: hexDesertRedMountains01
        elevation: '>0.84'
      - name: hexDesertRedMountains02
        elevation: '>0.81'
      - name: hexDesertRedMountains03
        elevation: '>0.78'
    terrains:
      # Savanna
      - name: hexDesertRedDirt00
        moisture: '>0.35'
        temperature: '<0.65'
      - name: hexDesertRedDirt01
        moisture: '>0.30'
        temperature: '<0.7'
      - name: hexDesertRedDirt02
        moisture: '>0.25'
        temperature: '<0.75'
      - name: hexDesertRedDirt03
        moisture: '>0.48'
        temperature: '<0.8'
      - name: hexDesertRedBase00
        moisture: '>0.45'
      - name: hexDesertRedBase01
        moisture: '>0.42'
      - name: hexDesertRedBase02
        moisture: '>0.39'
      - name: hexDesertRedBase03
        moisture: '>0.36'
      - name: hexDesertRedGrass00
        moisture: '>0.33'
      - name: hexDesertRedGrass01
        moisture: '>0.29'
      - name: hexDesertRedGrass02
        moisture: '>0.26'
      - name: hexDesertRedGrass03
  - type: Swamp
    walkCost: 0.7
    temperature: '<0.9'
    elevation: '<0.3'
    color: 4dcc8b
    terrains:
      - name: hexBog00
        moisture: '<0.81'
      - name: hexBog01
        moisture: '<0.83'
      - name: hexBog02
        moisture: '<0.85'
      - name: hexBog03
        moisture: '<0.87'
      - name: hexWetlands00
        temperature: '<0.3'
      - name: hexWetlands01
        temperature: '<0.4'
      - name: hexWetlands02
        temperature: '<0.5'
      - name: hexWetlands03
  - type: Forest
    walkCost: 1
    color: 2de442
    terrains:
      - name: hexScrublands00
        moisture: '<0.4'
      - name: hexScrublands01
        moisture: '<0.45'
      - name: hexScrublands02
        moisture: '<0.5'
      - name: hexScrublands03
        moisture: '<0.55'
      - name: hexPlains00
        temperature: '<0.5'
      - name: hexPlains01
        temperature: '<0.6'
      - name: hexPlains02
        temperature: '<0.65'
      - name: hexPlains03