wood:
  Pine:
    elevation: 0.1..0.3
    biomes: [Forest, Swamp, Cold]
  Ash:
    elevation: 0.1..0.3
    biomes: [Forest, Cold, ExtremeCold]
  Yew:
    elevation: 0.1..0.3
    biomes: [Jungle, Savanna, Forest]
  Ironwood:
    elevation: 0.1..0.3
    biomes: [Jungle, Forest, Swamp]
  Elderwood:
    elevation: 0.1..0.3
    biomes: [Forest, Cold, Savanna]
  Oak:
    elevation: 0.1..0.3
    biomes: [Forest, Savanna, Swamp, Cold]
fiber:
  Flax:
    elevation: 0.1..0.3
    biomes: [Forest, Savanna, Cold, Swamp]
  Linen:
    elevation: 0.1..0.3
    biomes: [Forest, Swamp, Savanna, Cold]
  Silk:
    elevation: 0.1..0.3
    biomes: [Jungle, Swamp, Savanna, Forest]
  SpiderSilk:
    elevation: 0.1..0.3
    biomes: [Jungle, Swamp, Savanna, Desert]
  MoonWeave:
    elevation: 0.1..0.3
    biomes: [Jungle, Savanna, Swamp, Desert]
  Cotton:
    elevation: 0.1..0.3
    biomes: [Savanna, Desert, Jungle, Forest]
ore:
  Copper:
    elevation: 0.3..0.5
    biomes: [ExtremeCold, Cold, Forest, Swamp]
  Iron:
    elevation: 0.3..0.5
    biomes: [Cold, Forest, Desert, Savanna, ExtremeCold]
  Gold:
    elevation: 0.3..0.5
    biomes: [DeepDesert, Desert, Cold, Swamp]
  Silver:
    elevation: 0.3..0.5
    biomes: [DeepDesert, Desert, Swamp, Savanna, Forest]
  Mithril:
    elevation: 0.3..0.5
    biomes: [ExtremeCold, Cold, Forest, Desert, Jungle]
  Adamantine:
    elevation: 0.3..0.5
    biomes: [ExtremeCold, DeepDesert, Cold, Desert, Jungle]
gem:
  RoughQuartz:
    elevation: 0.2..0.8
    biomes: [Desert, Cold, ExtremeCold, DeepDesert, Forest]
  Amber:
    elevation: 0.2..0.8
    biomes: [Desert, Savanna, DeepDesert, Jungle, Forest]
  Emerald:
    elevation: 0.2..0.8
    biomes: [DeepDesert, ExtremeCold, Cold, Desert, Swamp]
  Sapphire:
    elevation: 0.2..0.8
    biomes: [DeepDesert, ExtremeCold, Cold, Swamp, Jungle]
  Ruby:
    elevation: 0.2..0.8
    biomes: [Swamp, Desert, Savanna, Forest, Cold, Jungle]
  Starstone:
    elevation: 0.2..0.8
    biomes: [Jungle, Swamp, Cold, ExtremeCold, Forest, Desert]
leather:
  Rawhide:
    elevation: 0.1..0.5
    biomes: [Desert, Cold, ExtremeCold, DeepDesert, Forest]
  BeastHide:
    elevation: 0.3..0.8
    biomes: [Desert, Savanna, DeepDesert, Jungle, Forest]
  ThickHide:
    elevation: 0.1..0.8
    biomes: [DeepDesert, ExtremeCold, Cold, Desert, Swamp]
  ScaledLeather:
    elevation: 0.2..0.9
    biomes: [DeepDesert, ExtremeCold, Cold, Swamp, Jungle]
  OldLeather:
    elevation: 0.1..0.8
    biomes: [Swamp, Desert, Savanna, Forest, Cold, Jungle]
  FurLeather:
    elevation: 0.1..0.7
    biomes: [Jungle, Swamp, Cold, ExtremeCold, Forest, Desert]