references:
  harvesting_selection: &harvesting_selection
    - gem
    - ore
    - wood
    - fiber
    - leather
  harvestable_selection: &harvestable_selection
    - copper
    - iron
    - gold
    - silver
    - mithril
    - adamantine
    - pine
    - oak
    - ash
    - yew
    - ironwood
    - elderwood
    - flax
    - cotton
    - linen
    - silk
    - spidersilk
    - moonweave
    - roughquartz
    - amber
    - emerald
    - sapphire
    - ruby
    - starstone
    - rawhide
    - beasthide
    - thickhide
    - scaledleather
    - oldleather
    - furleather
strings:
  lang:
    key: lang
  capacity:
    key: capacity
  harvestable_capacity:
    key: harvestable_capacity
    handler: !<composite>
  harvesting:
    key: harvesting
    handler: !<selection>
      selections: *harvesting_selection
  harvestable:
    key: harvestable
    handler: !<selection>
      selections: *harvestable_selection
  harvesting_collect:
    key: harvesting_collect
  harvesting_begin:
    key: harvesting_begin
    handler: !<selection>
      selections: *harvesting_selection
  harvesting_harvested:
    key: harvesting_harvested
    handler: !<selection>
      selections: *harvesting_selection
  harvesting_amount:
    key: harvesting_amount
    handler: !<composite>
  close:
    key: close
  inventory:
    key: inventory

  #loading strings
  loading:
    key: loading
  loading_configuration:
    key: loading_configuration
  loading_generate_map:
    key: loading_generate_map
  loading_settlements:
    key: loading_settlements
  loading_roads:
    key: loading_roads
  loading_mines:
    key: loading_mines
  loading_game_state:
    key: loading_game_state
  loading_gui:
    key: loading_gui
  loading_player:
    key: loading_player
  loading_finalize:
    key: loading_finalize
  loading_textures:
    key: loading_textures
