wood:
  Pine:
    elevation: 0.1..0.3
    biomes: [Forest, Swamp, Cold]
  Ash:
    elevation: 0.1..0.3
    biomes: [ Forest, Cold, WitchForest ]
  Yew:
    elevation: 0.1..0.3
    biomes: [ MysticalForest, Forest ]
  Ironwood:
    elevation: 0.1..0.3
    biomes: [ MysticalForest, Forest, Swamp ]
  Elderwood:
    elevation: 0.1..0.3
    biomes: [ MysticalForest, Forest, Cold ]
  Oak:
    elevation: 0.1..0.3
    biomes: [ Forest, Swamp, Cold ]

fiber:
  Flax:
    elevation: 0.1..0.3
    biomes: [ Forest, Cold, Swamp ]
  Linen:
    elevation: 0.1..0.3
    biomes: [ Forest, Swamp, Cold ]
  Silk:
    elevation: 0.1..0.3
    biomes: [ MysticalForest, Swamp, Forest ]
  SpiderSilk:
    elevation: 0.1..0.3
    biomes: [ MysticalForest, Swamp, WitchForest ]
  MoonWeave:
    elevation: 0.1..0.3
    biomes: [ MysticalForest, Swamp ]
  Cotton:
    elevation: 0.1..0.3
    biomes: [ Forest, MysticalForest, WitchForest ]

ore:
  Copper:
    elevation: 0.3..0.5
    biomes: [ Cold, Forest, Swamp, WitchForest ]
  Iron:
    elevation: 0.3..0.5
    biomes: [ Cold, Forest, WitchForest ]
  Gold:
    elevation: 0.3..0.5
    biomes: [ WitchForest, Cold, Swamp ]
  Silver:
    elevation: 0.3..0.5
    biomes: [ WitchForest, Swamp, Forest ]
  Mithril:
    elevation: 0.3..0.5
    biomes: [ Cold, Forest, MysticalForest, WitchForest ]
  Adamantine:
    elevation: 0.3..0.5
    biomes: [ Cold, WitchForest, MysticalForest ]

gem:
  RoughQuartz:
    elevation: 0.2..0.8
    biomes: [ Cold, Forest, WitchForest ]
  Amber:
    elevation: 0.2..0.8
    biomes: [ Forest, MysticalForest ]
  Emerald:
    elevation: 0.2..0.8
    biomes: [ Cold, Swamp, WitchForest ]
  Sapphire:
    elevation: 0.2..0.8
    biomes: [ Cold, Swamp, MysticalForest, WitchForest ]
  Ruby:
    elevation: 0.2..0.8
    biomes: [ Swamp, Forest, Cold, MysticalForest, WitchForest ]
  Starstone:
    elevation: 0.2..0.8
    biomes: [ MysticalForest, Swamp, Cold, Forest ]

leather:
  Rawhide:
    elevation: 0.1..0.5
    biomes: [ Cold, Forest, WitchForest ]
  BeastHide:
    elevation: 0.3..0.8
    biomes: [ Forest, MysticalForest, WitchForest ]
  ThickHide:
    elevation: 0.1..0.8
    biomes: [ Cold, Swamp, WitchForest ]
  ScaledLeather:
    elevation: 0.2..0.9
    biomes: [ Cold, Swamp, MysticalForest, WitchForest ]
  OldLeather:
    elevation: 0.1..0.8
    biomes: [ Swamp, Forest, Cold, MysticalForest ]
  FurLeather:
    elevation: 0.1..0.7
    biomes: [ MysticalForest, Swamp, Cold, Forest ]