biomes:
  - name: Water # Atlas name
    elevation: -0.15
    color: 158fc0
    terrains:
      # Default water
      - name: Water9
        elevation: -0.25
        temperature: 0.4
      - name: Water8
        elevation: -0.2
        temperature: 0.4
      - name: Water1
        elevation: -0.17
        temperature: 0.4
      - name: BeachSand10
        temperature: 0.4
      # Warm water
      - name: Water7
        elevation: -0.25
      - name: Water6
        elevation: -0.2
      - name: Water1
        elevation: -0.17
      - name: BeachSand2
  - name: Savanna
    moisture: 0.3
    temperature: 0.5
    color: a86e0d
    terrains:
      # Savanna
      - name: DrySoil1
        temperature: 0.4
        elevation: 0.4
      - name: DrySoil2
        temperature: 0.4
        elevation: 0.75
      - name: DrySoil3
  - name: Desert
    moisture: 0.3
    temperature: 0.7
    color: e5c359
    terrains:
      - name: DesertSand1
        temperature: 0.5
        elevation: 0.3
      - name: DesertSand8
        temperature: 0.6
        elevation: 0.5
      - name: Sand24
        elevation: 0.7
      - name: Sand22
  - name: DeepDesert
    moisture: 0.3
    color: e5b00b
    # Dunes
    terrains:
      - name: RippledSand1
        elevation: 0.2
      - name: RippledSand5
        elevation: 0.5
      - name: RippledSand10
  - name: Snow
    temperature: 0.2
    color: a9c5c5
    terrains:
      - name: Snow2
        temperature: 0.11
      - name: Snow13
        temperature: 0.15
      - name: DirtySnow1
  - name: Ice
    temperature: 0.1
    color: 3dc5c5
    terrains:
      - name: Ice10
        temperature: 0.05
      - name: Ice3
        temperature: 0.08
      - name: Ice12
  - name: Swamp
    temperature: 0.4
    elevation: 0.3
    color: 16a659
    terrains:
      - name: Mud1
        moisture: 0.3
      - name: Mud2
        moisture: 0.6
      - name: Mud3
  - name: Jungle
    temperature: 0.6
    elevation: 0.5
    color: 4fae0c
    terrains:
      - name: JungleFloor4
        moisture: 0.2
      - name: JungleFloor1
        moisture: 0.6
      - name: JungleFloor2
        elevation: 0.5
      - name: JungleFloor3
  - name: Forest # forest is the most common biome and also serves as fallback
    color: 5fae61
    terrains:
      - name: Grass1
        elevation: 0.2
      - name: Grass2
        elevation: 0.4
      - name: Grass3
        elevation: 0.6
      - name: Grass4


