biomes:
  - type: Volcanic
    color: ff4400
    walkCost: 0.85
    temperature: '>0.9'
    terrains:
      # ground
      - index: 30
        elevation: '0.15..0.3'
        moisture: '<0.5'
      - index: 31
        elevation: '0.15..0.3'
        moisture: '>0.5'