materials:
  - id: BASEMat_01
    useColorNoise: false
    smallNoiseFreq: 0
    largeNoiseFreq: 0
    leaves:
      texture: tropicalDiffuse01
      normal:
      metallic: 0
      smoothness: 0.2
      useFlatColor: false
      baseColor: ffffff
      noiseColor: ffffff
      noiseLargeColor: ffffff
      normalStrength: 0
    trunk:
      texture: tropicalDiffuse01
      emissive:
      useFlatColor: false
      metallic: 0
      smoothness: 0.2
      baseColor: 140500
      noiseColor: 000000


  - id: Branches_01
    useColorNoise: false
    smallNoiseFreq: 0
    largeNoiseFreq: 0
    leaves:
      texture: Branches_01
      normal:
      metallic: 0.144
      smoothness: 0.484
      useFlatColor: false
      baseColor: ffffff
      noiseColor: ffffff
      noiseLargeColor: ffffff
      normalStrength: 0
    trunk:
      texture: Branches_01
      emissive:
      useFlatColor: false
      metallic: 0
      smoothness: 0.2
      baseColor: ffffff
      noiseColor: ffffff
      emissiveColor: 000000
      normalStrength: 0


  - id: Flowers_Flat_Mat_01
    useColorNoise: false
    smallNoiseFreq: 0
    largeNoiseFreq: 0
    leaves:
      texture: FlowersFlat_01
      normal: FlowersFlat_01_Normals
      metallic: 0
      smoothness: 0.4
      useFlatColor: false
      baseColor: ffffff
      noiseColor: 8FA100
      noiseLargeColor: ffffff
      normalStrength: 0.5


  - id: Flowers_Flat_Mat_02
    useColorNoise: true
    smallNoiseFreq: 10
    largeNoiseFreq: 0.24
    leaves:
      texture: FlowersFlat_01
      normal: FlowersFlat_01_Normals
      metallic: 0
      smoothness: 0.4
      useFlatColor: true
      baseColor: A82525
      noiseColor: FF1200
      noiseLargeColor: 894449
      normalStrength: 0.5

  - id: Flowers_Plant_Mat_01
    useColorNoise: true
    smallNoiseFreq: 10
    largeNoiseFreq: 0.1
    leaves:
      texture: tropicalDiffuse01
      metallic: 0
      smoothness: 0.4
      useFlatColor: true
      baseColor: FF0000
      noiseColor: FF1D00
      noiseLargeColor: 140500

  - id: Grass_Med_Mat_01
    useColorNoise: true
    smallNoiseFreq: 10
    largeNoiseFreq: 0.1
    leaves:
      texture: Grass_Mid_01
      normal: Grass_Mid_01_Normals
      metallic: 0
      smoothness: 0.4
      useFlatColor: true
      baseColor: 1A4800
      noiseColor: 8FA100
      noiseLargeColor: 484400
      normalStrength: 0.5

  - id: Grass_Short_Mat_01
    useColorNoise: true
    smallNoiseFreq: 10
    largeNoiseFreq: 0.1
    leaves:
      texture: Grass_Short_01
      normal: Grass_Short_01_Normals
      metallic: 0
      smoothness: 0.4
      useFlatColor: true
      baseColor: 1A4800
      noiseColor: 8FA100
      noiseLargeColor: 484400
      normalStrength: 0.5

  - id: Grass_Tall_Mat_01
    useColorNoise: true
    smallNoiseFreq: 10
    largeNoiseFreq: 0.1
    leaves:
      texture: Grass_01
      normal: Grass_01_Normals
      metallic: 0
      smoothness: 0.2
      useFlatColor: true
      baseColor: 1A4800
      noiseColor: 8FA100
      noiseLargeColor: 484400
      normalStrength: 0.5

  - id: Ground_Cover_Mat_01
    useColorNoise: false
    leaves:
      texture: GroundCover_01
      normal: GroundCover_01_Normals
      metallic: 0
      smoothness: 0.2
      useFlatColor: false
      baseColor: 1A4800
      noiseColor: AFC500
      noiseLargeColor: FFFFFF
      normalStrength: 0.5

  - id: Palm_Mat_01
    useColorNoise: true
    smallNoiseFreq: 1
    largeNoiseFreq: 0.3
    leaves:
      texture: Leaf_Palm_01
      metallic: 0.099
      smoothness: 0.49
      useFlatColor: false
      baseColor: FFFFFF
      noiseColor: D0FFA2
      noiseLargeColor: FFC677
    trunk:
      texture: Palm_Bark_01
      useFlatColor: false
      metallic: 0
      smoothness: 0.2
      baseColor: ffffff
      noiseColor: ffffff
      emissiveColor: 000000
      normalStrength: 0

  - id: Palm_Mat_02
    useColorNoise: true
    smallNoiseFreq: 1
    largeNoiseFreq: 0.03
    leaves:
      texture: Leaf_Banana_01
      normal: Leaf_Banana_01_Normals
      metallic: 0.144
      smoothness: 0.507
      useFlatColor: false
      baseColor: FFFFFF
      noiseColor: D7FDB2
      noiseLargeColor: FFB086
      normalStrength: 0.5
    trunk:
      texture: Palm_Bark_01
      useFlatColor: false
      metallic: 0
      smoothness: 0.2
      baseColor: ffffff
      noiseColor: ffffff
      emissiveColor: 000000
      normalStrength: 0

  - id: Palm_Mat_03
    useColorNoise: true
    smallNoiseFreq: 1
    largeNoiseFreq: 0.03
    leaves:
      texture: Leaf_Detailed_01
      normal: Leaf_Detailed_01_Normals
      metallic: 0.144
      smoothness: 0.484
      useFlatColor: false
      baseColor: FFFFFF
      noiseColor: D7FDB2
      noiseLargeColor: FFB086
      normalStrength: 0.5
    trunk:
      texture: Palm_Bark_01
      useFlatColor: false
      metallic: 0
      smoothness: 0.2
      baseColor: ffffff
      noiseColor: ffffff
      emissiveColor: 000000
      normalStrength: 0

  - id: Palm_Mat_04
    useColorNoise: true
    smallNoiseFreq: 1
    largeNoiseFreq: 0.03
    leaves:
      texture: Leaf_Fern_01
      normal: Leaf_Fern_01_Normals
      metallic: 0.144
      smoothness: 0.484
      useFlatColor: false
      baseColor: FFFFFF
      noiseColor: BDFF88
      noiseLargeColor: FF1F00
      normalStrength: 0.5
    trunk:
      texture: Palm_Bark_01
      useFlatColor: false
      metallic: 0
      smoothness: 0.2
      baseColor: ffffff
      noiseColor: ffffff
      emissiveColor: 000000
      normalStrength: 0

  - id: Palm_Mat_05
    useColorNoise: true
    smallNoiseFreq: 1
    largeNoiseFreq: 0.03
    leaves:
      texture: Leaf_Square_01
      normal: Leaf_Square_01_Normals
      metallic: 0.144
      smoothness: 0.484
      useFlatColor: false
      baseColor: FFFFFF
      noiseColor: D7FDB2
      noiseLargeColor: FF9A64
      normalStrength: 0.5
    trunk:
      texture: Palm_Bark_01
      useFlatColor: false
      metallic: 0
      smoothness: 0.2
      baseColor: ffffff
      noiseColor: ffffff
      emissiveColor: 000000
      normalStrength: 0

  - id: Palm_Mat_06
    useColorNoise: true
    smallNoiseFreq: 1
    largeNoiseFreq: 0.03
    leaves:
      texture: Leaf_Fan_01
      normal: Leaf_Fan_normals
      metallic: 0
      smoothness: 0.2
      useFlatColor: false
      baseColor: FFFFFF
      noiseColor: D7FDB2
      noiseLargeColor: FF9A64
      normalStrength: 0.5
    trunk:
      texture: Palm_Bark_01
      useFlatColor: false
      metallic: 0
      smoothness: 0.2
      baseColor: ffffff
      noiseColor: ffffff
      emissiveColor: 000000
      normalStrength: 0

  - id: Palm_Mat_07
    useColorNoise: true
    smallNoiseFreq: 1
    largeNoiseFreq: 0.03
    leaves:
      texture: Leaf_Palm_01
      normal: Leaf_Palm_01_Normals
      metallic: 0.099
      smoothness: 0.49
      useFlatColor: false
      baseColor: FFFFFF
      noiseColor: D3FF5D
      noiseLargeColor: BE473C
      normalStrength: 0.5
    trunk:
      texture: Palm_Bark_02
      useFlatColor: false
      metallic: 0
      smoothness: 0.2
      baseColor: ffffff
      noiseColor: ffffff
      emissiveColor: 000000
      normalStrength: 0

  - id: Palm_Red_Mat_01
    useColorNoise: true
    smallNoiseFreq: 1
    largeNoiseFreq: 0.03
    leaves:
      texture: Leaf_Palm_01
      normal: Leaf_Palm_01_Normals
      metallic: 0.05
      smoothness: 0.3
      useFlatColor: false
      baseColor: FFFFFF
      noiseColor: FF5555
      noiseLargeColor: FFBFBF
      normalStrength: 0.5
    trunk:
      texture: Palm_Bark_01
      useFlatColor: false
      metallic: 0
      smoothness: 0.2
      baseColor: ffffff
      noiseColor: ffffff
      emissiveColor: 000000
      normalStrength: 0

  - id: Pohutukawa_Mat_01
    useColorNoise: true
    smallNoiseFreq: 1
    largeNoiseFreq: 0.03
    leaves:
      texture: pohutukawaLeaf
      metallic: 0
      smoothness: 0.2
      useFlatColor: false
      baseColor: FFFFFF
      noiseColor: CAFFA2
      noiseLargeColor: FFA0A0
      normalStrength: 0.5
    trunk:
      texture: tropicalDiffuse01
      useFlatColor: false
      metallic: 0
      smoothness: 0.2
      baseColor: ffffff
      noiseColor: ffffff
      emissiveColor: 000000
      normalStrength: 0

  - id: Seaweed_Mat_01
    useColorNoise: true
    smallNoiseFreq: 9.71
    largeNoiseFreq: 1.91
    leaves:
      texture: SeaWeed_Texture_01
      normal: Seaweed_Normals_01
      metallic: 0
      smoothness: 0
      useFlatColor: false
      baseColor: FFFFFF
      noiseColor: C6D44F
      noiseLargeColor: 97BE00
      normalStrength: 0.5

  - id: Tree_Mat_01
    useColorNoise: true
    smallNoiseFreq: 15
    largeNoiseFreq: 0.5
    leaves:
      texture: leafPatch
      metallic: 0
      smoothness: 0.2
      useFlatColor: true
      baseColor: 399314
      noiseColor: 2B4100
      noiseLargeColor: 6D7D02
      normalStrength: 0.5

  - id: Tree_Mat_01_Small
    useColorNoise: true
    smallNoiseFreq: 15
    largeNoiseFreq: 0.5
    leaves:
      texture: leafPatch
      metallic: 0
      smoothness: 0.2
      useFlatColor: true
      baseColor: 149314
      noiseColor: 2B4100
      noiseLargeColor: 6D7D02
      normalStrength: 0.5

  - id: Tree_Mat_02
    useColorNoise: true
    smallNoiseFreq: 15
    largeNoiseFreq: 0.5
    leaves:
      texture: leafPatch_02
      metallic: 0
      smoothness: 0.2
      useFlatColor: true
      baseColor: 4F7B02
      noiseColor: 283A05
      noiseLargeColor: 6D7D02
      normalStrength: 0.5
    trunk:
      texture: tropicalDiffuse01
      useFlatColor: false
      metallic: 0
      smoothness: 0.183
      baseColor: ffffff
      noiseColor: ffffff
      emissiveColor: 000000
      normalStrength: 0

  - id: Tree_Mat_02_Small
    useColorNoise: true
    smallNoiseFreq: 15
    largeNoiseFreq: 0.5
    leaves:
      texture: leafPatch_02
      metallic: 0
      smoothness: 0.2
      useFlatColor: true
      baseColor: 659314
      noiseColor: 2B4100
      noiseLargeColor: 6D7D02
      normalStrength: 0.5
    trunk:
      texture: tropicalDiffuse01
      useFlatColor: false
      metallic: 0
      smoothness: 0.183
      baseColor: ffffff
      noiseColor: ffffff
      emissiveColor: 000000
      normalStrength: 0

  - id: Tree_Mat_03
    useColorNoise: false
    smallNoiseFreq: 0.788
    largeNoiseFreq: 0.68
    leaves:
      texture: leafPatch_03
      normal: leafPatch_03_Normals
      metallic: 0.124
      smoothness: 0.263
      useFlatColor: true
      baseColor: 3C541B
      noiseColor: 4F7818
      noiseLargeColor: 606E00
      normalStrength: 0.5
    trunk:
      texture: tropicalDiffuse01
      useFlatColor: false
      metallic: 0
      smoothness: 0.183
      baseColor: ffffff
      noiseColor: ffffff
      emissiveColor: 000000
      normalStrength: 0